# Generated by Django 5.2.14 on 2026-05-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_stripe_webhook_receipts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentevent',
            new_name='payments_pa_payment_ec2b3d_idx',
            old_name='payments_pa_payment__40db44_idx',
        ),
        migrations.RenameIndex(
            model_name='refundrequest',
            new_name='payments_re_payment_58c7e0_idx',
            old_name='payments_re_payment__9ed7f2_idx',
        ),
        migrations.RenameIndex(
            model_name='refundrequest',
            new_name='payments_re_user_id_27b6a3_idx',
            old_name='payments_re_user_st_8d0c26_idx',
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
    ]
