# Generated by Django 5.2.14 on 2026-05-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_refund_request_processing_failed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
