version: "3.9"

services:
  web:
    build: .
    image: food-payment-web:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=False
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: brfn
      POSTGRES_USER: brfn
      POSTGRES_PASSWORD: brfnpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
