# Generated by Django 5.2.9 on 2026-04-16 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_qualityinspection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_type", models.CharField(choices=[("recommendation", "Recommendation"), ("forecasting", "Forecasting"), ("quality_freshness", "Quality Freshness"), ("quality_multi_output", "Quality Multi Output")], max_length=40)),
                ("version_name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("artifact", models.FileField(upload_to="ai_models/")),
                ("metadata_json", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="uploaded_ai_models", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ForecastSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weekly_demand", models.CharField(max_length=255)),
                ("forecast_next_week", models.PositiveIntegerField()),
                ("recommended_stock", models.PositiveIntegerField()),
                ("trend", models.CharField(max_length=20)),
                ("confidence", models.CharField(max_length=20)),
                ("explanation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("producer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="producer_forecast_snapshots", to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="forecast_snapshots", to="products.product")),
                ("viewer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="forecast_snapshots", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="QualityInspectionOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("previous_grade", models.CharField(max_length=1)),
                ("new_grade", models.CharField(choices=[("A", "Grade A"), ("B", "Grade B"), ("C", "Grade C")], max_length=1)),
                ("previous_freshness_label", models.CharField(max_length=20)),
                ("new_freshness_label", models.CharField(choices=[("fresh", "Fresh"), ("rotten", "Rotten"), ("unknown", "Unknown")], max_length=20)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("inspection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="overrides", to="products.qualityinspection")),
                ("overridden_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quality_overrides", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="RecommendationEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("impression", "Impression"), ("click", "Click")], max_length=20)),
                ("source_page", models.CharField(choices=[("product_list", "Product List"), ("ai_insights", "AI Insights"), ("quick_reorder", "Quick Reorder")], max_length=30)),
                ("rank", models.PositiveIntegerField(default=1)),
                ("score", models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("producer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="producer_recommendation_events", to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recommendation_events", to="products.product")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recommendation_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
